### ISSUE TITLE
Docker-compose generator

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo-docker#4]
Since Buffalo already generates a Docker file, it can be a great addition to generate a docker-compose.yml file too.

This file will be generated from the DB params provided to the `new` command.

Here is a raw template for a postgres version (just an idea, not the final thing):

```
version: '3'

services:
  db:
    container_name: {{ .opts.Name.Title }}-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{ .opts.Name.Title }}_${GO_ENV:-development}
    volumes:
      - ./db:/var/lib/postgresql/data
```
